spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fakedb
    username: root
    password: Irisviel95
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  jackson:
    serialization:
      fail-on-empty-beans: false
redis:
  database: Davide-free-db
  password: npDlog6dLJqm56NCS9ifOewYy461TfBm
  host: redis-15639.c267.us-east-1-4.ec2.cloud.redislabs.com
  port: 15639
